
repo = 'gitrhythm/brew:0.1'
container = 'brew2'

task default: :l   # docker image ls

### イメージ操作系 ###

# build
desc "docker build -t #{repo} ."
task :b do
  unless image_created?(repo)
    puts 'イメージをビルドしています'
    system "docker build -t #{repo} . > /dev/null"
  end
end

# clean
desc "docker image rm #{repo}"
task clean: :stop do
  if container_created?(container)
    puts 'コンテナを削除しています'
    system "docker container rm #{container} > /dev/null"
  end

  if image_created?(repo)
    puts 'イメージを削除しています'
    system "docker image rm #{repo}"
  end
end

### コンテナ操作系 ###

# start
desc "docker container run -d -it --name #{container} #{repo} /bin/bash"
task start: :b do
  unless container_created?(container)
    puts 'コンテナを作成しています'
    system "docker container create -it --name #{container} #{repo}"
  end

  unless container_running?(container)
    puts 'コンテナを起動しています'
    system "docker container start #{container} > /dev/null"
  end
end

# stop
desc "docker container stop #{container}"
task :stop do
  if container_running?(container)
    puts 'コンテナを停止しています'
    system "docker container stop #{container} > /dev/null"
  end
end

# login
desc "docker exec -it #{container} /bin/bash"
task login: [:b, :start] do
  system "docker exec -it #{container} /bin/bash"
end

### 状態表示系 ###

# image list
desc "image ls"
task :l do
  system 'docker image ls'
end

# container ps
desc "container ps"
task :ps do
  system 'docker container ps'
end

# container ps -a
desc "container ps -a"
task :psa do
  system 'docker container ps -a'
end

# helpers

def image_created?(repo)
  result = `docker image ls #{repo} | tail -n +2`
  !result.empty?
end

def container_created?(container)
  result = `docker container ps -a | grep #{container}`
  !result.empty?
end

def container_running?(container)
  result = `docker container ps | grep #{container}`
  !result.empty?
end
