version: '3.8'
services:
  ruby:
    container_name: ruby
    build: .
    volumes:
      - ./app:/work
    command: /bin/bash

# docker compose up
# docker compose stop
# docker compose run ruby /bin/bash --login
